version: '3.9'

services:

  db:
    image: postgres:16.3
    container_name: gadget_plus
    restart: always
    volumes:
      - ./sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=gadget_plus
      - POSTGRES_USER=debuggeandoideas
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"